Task 2 short ways
makar-pelogeiko/high-performance-graph-analysis-course pull request #2
Opened 2022-05-10 19:05 UTC by makar-pelogeiko

# Задача 2. Реализация поиска кратчайших путей

* **Мягкий дедлайн**: ---
* **Жёсткий дедлайн**: 14.04.2022, 23:59
* Полный балл: 15

## Задача

Везде считаем, что вершины графа занумерованы подряд с нуля.
Обратите внимание на то, что про граф заранее не известно, есть ли в нём циклы отрицательного веса.

- [ ] Используя pygraphblas реализовать функцию поиска кратчайших путей в ориентированном графе из заданной вершины. 
  - [ ] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и номер стартовой вершины.
  - [ ] Функция возвращает массив, где для каждой вершины указано расстояние до неё от указанной стартовой вершины. Если вершина не достижима, то значение соответствующей ячейки равно -1.
- [ ] Используя pygraphblas реализовать функцию поиска кратчайших путей в ориентированном графе из нескольких заданных вершин.
  - [ ] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и массив номеров стартовых вершин.
  - [ ] Функция возвращает массив пар: вершина, и массив, где для каждой вершины указано расстояние до неё из указанной. Если вершина не достижима, то значение соответствующей ячейки равно -1.
- [ ] Добавить необходимые тесты.

2022-05-28 18:18 UTC, gsvgit commented on project/shortPath.py
> +    for _ in range(matrix_graph.nrows):
Можно ли как-то делать меньше итераций?

2022-05-29 10:04 UTC, makar-pelogeiko commented on project/shortPath.py
> +    for _ in range(matrix_graph.nrows):
можно сделать обход похожий на тот, что был в BFS

2022-05-30 07:53 UTC, gsvgit requested changes

2022-05-30 07:53 UTC, gsvgit commented on project/shortPath.py
> +    while prev_nnz != visited.nvals:
Кажется мне, что тесты у Вас не все важные случаи покрывают.

2022-05-30 17:32 UTC, makar-pelogeiko commented on project/shortPath.py
> +    while prev_nnz != visited.nvals:
Я правильно понял, что Вы про отрицательные циклы?

2022-06-06 06:10 UTC, gsvgit commented on project/shortPath.py
> +    while prev_nnz != visited.nvals:
Да. Что-то кажется, что так, как у Вас сейчас написано, отрицательные циклы нормально работать не будут.

2022-06-09 15:59 UTC, gsvgit approved these changes

2023-03-20 19:57 UTC, merged